import Head from "next/head";
import React from "react";
import { Content } from "./Styled";

const Container = ({ children, title }) => {
  return (
    <>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Content>{children}</Content>
    </>
  );
};

export default Container;
